<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_css_img-fluid</name>
   <tag></tag>
   <elementGuidId>2d76f6ea-afba-458f-bcb0-1b70254ffb3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='team']/div/div/div/div[7]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1edec551-aba8-4a8a-8f56-86bb5112860d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://project-ubah.open/images/8af0a9162e82c4b99360ad5c5b9f2610.jpg</value>
      <webElementGuid>c74be480-96de-45eb-a6e0-66db4febc563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>ac3ba399-64fa-461a-9cac-0eafecf44b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;team&quot;)/div[@class=&quot;container aos-init aos-animate&quot;]/div[@class=&quot;container mt-5&quot;]/div[@class=&quot;row gy-4&quot;]/div[@class=&quot;col-xl-3 col-md-6 d-flex aos-init aos-animate&quot;]/div[@class=&quot;member&quot;]/a[1]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>494cf9c5-b102-4bc8-babb-3d7cc3409bf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='team']/div/div/div/div[7]/div/a/img</value>
      <webElementGuid>156a7545-7157-4833-b969-457fc8c1c3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://project-ubah.open/images/8af0a9162e82c4b99360ad5c5b9f2610.jpg')]</value>
      <webElementGuid>3a4d9dbd-ae47-4453-8f08-a5195faf1558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/a/img</value>
      <webElementGuid>897e94b7-f08e-4e81-9980-75a0a423b3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://project-ubah.open/images/8af0a9162e82c4b99360ad5c5b9f2610.jpg']</value>
      <webElementGuid>d4d20869-9ca9-4d64-9fa3-c25b614dae6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
