<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DiaryMe</name>
   <tag></tag>
   <elementGuidId>90aaf7e7-4a9b-432e-81a7-7c883ae0090f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.d-none.d-lg-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7034310a-20fe-44ce-873a-ba1572e19aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-lg-block</value>
      <webElementGuid>d887d63e-d0ea-42e1-9414-13dec9f2f484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DiaryMe</value>
      <webElementGuid>abcd32d8-a7e6-478b-b051-42b4d29c7181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;d-flex align-items-center justify-content-between&quot;]/a[@class=&quot;logo d-flex align-items-center&quot;]/span[@class=&quot;d-none d-lg-block&quot;]</value>
      <webElementGuid>ff66ccb0-3581-4dfc-a004-373b3741113f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/a/span</value>
      <webElementGuid>0217e1d6-8ff2-4423-a275-020c25f79ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/preceding::span[1]</value>
      <webElementGuid>a3690797-8e9e-4695-a1ec-10e82f8f4bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[2]/preceding::span[2]</value>
      <webElementGuid>fd652537-4520-4ede-ad6c-6b20e8035d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DiaryMe']/parent::*</value>
      <webElementGuid>2df63ff8-fd97-4524-9535-df16c4863a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>9d75394a-d10a-4603-bb3b-398ad5417746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'DiaryMe' or . = 'DiaryMe')]</value>
      <webElementGuid>15e48e8a-76c2-4dd7-b60a-0c64ff81d231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
