<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_css_img-fluid</name>
   <tag></tag>
   <elementGuidId>dc399e77-7d1d-4eb5-9eec-ea604f22a85e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='team']/div/div/div/div[7]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>68681dcd-9fe7-4647-a702-d96370bb4c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://project-ubah.open/images/8af0a9162e82c4b99360ad5c5b9f2610.jpg</value>
      <webElementGuid>730011cb-6941-40ef-812a-ec6ee40423e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>f966c3b5-70d5-4214-88dc-8254753bfc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;team&quot;)/div[@class=&quot;container aos-init aos-animate&quot;]/div[@class=&quot;container mt-5&quot;]/div[@class=&quot;row gy-4&quot;]/div[@class=&quot;col-xl-3 col-md-6 d-flex aos-init aos-animate&quot;]/div[@class=&quot;member&quot;]/a[1]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>8b9a4e97-1628-44e0-901a-6ac0464581b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='team']/div/div/div/div[7]/div/a/img</value>
      <webElementGuid>148d23ea-cecb-4b10-93d7-2ac854a3cfb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://project-ubah.open/images/8af0a9162e82c4b99360ad5c5b9f2610.jpg')]</value>
      <webElementGuid>eba2b7f0-d950-4120-92b4-9f09b3be7e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/a/img</value>
      <webElementGuid>cca1a884-b815-48db-914f-810736e16802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://project-ubah.open/images/8af0a9162e82c4b99360ad5c5b9f2610.jpg']</value>
      <webElementGuid>61f4effa-03a3-4c04-8162-505979610f1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
