<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mulai Membaca</name>
   <tag></tag>
   <elementGuidId>4bd5df6f-3d3b-44e7-ab5d-358d68806a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='hero']/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn-get-started</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24a703ae-b892-4453-a8a9-a8d2e0ef4748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/karya</value>
      <webElementGuid>599bfe2e-c555-4698-985c-90178924f59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-get-started</value>
      <webElementGuid>a6afc4b7-e407-4232-b3f6-22d7eb8bbc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mulai Membaca</value>
      <webElementGuid>85031015-f529-415f-8494-cdd4f0eda240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hero&quot;)/div[@class=&quot;container position-relative&quot;]/div[@class=&quot;row gy-5 aos-init aos-animate&quot;]/div[@class=&quot;col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center text-center text-lg-start&quot;]/div[@class=&quot;d-flex justify-content-center justify-content-lg-start&quot;]/a[@class=&quot;btn-get-started&quot;]</value>
      <webElementGuid>ed92e5af-ac53-4fe4-bcbb-37188bf47fbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='hero']/div/div/div/div/a</value>
      <webElementGuid>05e4d3b6-c654-46ba-ad76-a84ca6de2b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mulai Membaca')]</value>
      <webElementGuid>c6ee6659-d7e5-4dce-8bed-655c54628820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DiaryMe'])[4]/following::a[1]</value>
      <webElementGuid>9e8e84f4-9977-46b3-9f87-2611854a4b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DiaryMe'])[3]/following::a[1]</value>
      <webElementGuid>762523f5-febc-4867-99a4-14f2e6b80cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::a[1]</value>
      <webElementGuid>6e4f0e26-3c4a-4721-8848-996f59bd4392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::a[2]</value>
      <webElementGuid>e4ad8071-1739-426b-a6a8-88f836f1db54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mulai Membaca']/parent::*</value>
      <webElementGuid>0e0e9594-13ca-4344-a038-ad9189375156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/karya')])[2]</value>
      <webElementGuid>cffaad07-ac2f-4fc2-898e-c11ac3307e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>600f8c14-ba96-443f-bb94-0b6676d6a8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/karya' and (text() = 'Mulai Membaca' or . = 'Mulai Membaca')]</value>
      <webElementGuid>143bddef-58f6-4e17-b7c0-1649c4022803</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
