<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_css_img-fluid</name>
   <tag></tag>
   <elementGuidId>7354af3e-f600-4c2e-a072-a3208fee9527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='team']/div/div/div/div[7]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ac9605d6-6a78-4691-92d9-e8c32f00ac0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://project-ubah.open/images/8af0a9162e82c4b99360ad5c5b9f2610.jpg</value>
      <webElementGuid>5aaa5b24-a7d6-4744-aee3-55736bab3f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>72a58b1a-7bc2-4dc6-93aa-d2818ef05260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;team&quot;)/div[@class=&quot;container aos-init aos-animate&quot;]/div[@class=&quot;container mt-5&quot;]/div[@class=&quot;row gy-4&quot;]/div[@class=&quot;col-xl-3 col-md-6 d-flex aos-init aos-animate&quot;]/div[@class=&quot;member&quot;]/a[1]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>2e13cc9e-b625-4dc9-8caa-f8488cd5161b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='team']/div/div/div/div[7]/div/a/img</value>
      <webElementGuid>76bbb06d-6906-4e86-b0b3-72e9827bf8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://project-ubah.open/images/8af0a9162e82c4b99360ad5c5b9f2610.jpg')]</value>
      <webElementGuid>ef7fb70b-6692-4381-8e93-243bce1a3d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/a/img</value>
      <webElementGuid>5570483d-ef60-4d24-b4a3-c16cc2dbc7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://project-ubah.open/images/8af0a9162e82c4b99360ad5c5b9f2610.jpg']</value>
      <webElementGuid>724bc68d-9e38-4340-9c58-9cbb4d018415</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
