<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_css_img-fluid</name>
   <tag></tag>
   <elementGuidId>eae548ea-9a25-463e-af08-2c353ba75308</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='team']/div/div/div/div[7]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>035ffe5a-93f0-4c59-9dd0-f1252912de7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://project-ubah.open/images/8af0a9162e82c4b99360ad5c5b9f2610.jpg</value>
      <webElementGuid>d3f3ba5a-e49a-46b0-be8f-b0b03b415d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>87f0a43e-ff3e-431e-afd6-7d333e3b8197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;team&quot;)/div[@class=&quot;container aos-init aos-animate&quot;]/div[@class=&quot;container mt-5&quot;]/div[@class=&quot;row gy-4&quot;]/div[@class=&quot;col-xl-3 col-md-6 d-flex aos-init aos-animate&quot;]/div[@class=&quot;member&quot;]/a[1]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>e46cebb3-60a4-409f-8525-723be3f7c050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='team']/div/div/div/div[7]/div/a/img</value>
      <webElementGuid>a5b4e77c-cf2b-4850-98fe-b8260d80dc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://project-ubah.open/images/8af0a9162e82c4b99360ad5c5b9f2610.jpg')]</value>
      <webElementGuid>d790b684-794e-408a-9b2d-3ac0498762e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/a/img</value>
      <webElementGuid>6c880565-b826-4eda-afc1-be6c163b16c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://project-ubah.open/images/8af0a9162e82c4b99360ad5c5b9f2610.jpg']</value>
      <webElementGuid>f05d7b81-3856-4e84-94e3-2f2acb85342f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
