<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Open Hours_subject</name>
   <tag></tag>
   <elementGuidId>63411a00-dbde-4785-bcbe-183d50271768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subject</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subject']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6dbfc8aa-58ec-4482-92a4-165044b5a581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b04441d-ed59-4cc7-a721-fb38f956ea77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>183a9880-f7d3-4f00-b039-ec213c1a9a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subject</value>
      <webElementGuid>a9dd4a37-c993-4a53-b470-ef9a65403ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subject</value>
      <webElementGuid>51bea83c-7558-4261-b25c-5b2be3335512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Subject</value>
      <webElementGuid>30cb9485-d76e-4e7f-b874-e827413c636e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subject&quot;)</value>
      <webElementGuid>48a010e9-31a9-469d-a3ae-d722840d5c66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='subject']</value>
      <webElementGuid>3e6f8513-03e6-4d75-8e50-2242e50ec4a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='contact']/div/div[2]/div[2]/form/div[2]/input</value>
      <webElementGuid>f188dcc4-1929-4f64-af36-a9c06f86e4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d650cf27-c1a8-43d1-b1fa-14084f261687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'subject' and @id = 'subject' and @placeholder = 'Subject']</value>
      <webElementGuid>22f0158b-2ebb-494e-afb3-247f286632cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
